### ISSUE TITLE
Only works in /barbones-toolchain/

### ISSUE THREAD

**Issue by Coretool** [rm-hull/barebones-toolchain#1]
The command " i686-elf-gcc" only works in the barbones-toolchain directory.

**Comment by rm-hull** [comment]
Hi, can you give me a few details please:
- What is the exact error message you are seeing when you run it outside of the barbones-toolchain directory ?
- Which host OS are you using and what is the output of `uname -a` ?
- Have you run `. ./setenv.sh` and what output did it display?
- What is the value of `echo $PATH` ?
