### ISSUE TITLE
More Features?

### ISSUE THREAD

**Issue by amanuel2** [rm-hull/barebones-toolchain#3]
I am currently very depedant on this github project for my Cross Compiler.. As i improve in the future , i will be developing on multiple arch's rather than just x86 and x86-64 .. May you consider adding more arch's please? For example : mips , arm , arm64, etc..

**Comment by rm-hull** [comment]
It already supports arm/arm64 but not mips (although it should be quite simple)

The versions are a bit out of date, so maybe it's time for a bit if a refresh

**Comment by amanuel2** [comment]
@rm-hull Hmm , confusing. I am only seeing x86 and x86-64 here: https://github.com/rm-hull/barebones-toolchain/tree/master/cross/i686 ... Or did i miss something?

**Comment by rm-hull** [comment]
Ah, so the first i686 or x86_64 is the host environment and the subdirectory of i686-elf or arm-none-eabi denote the target environment.

**Comment by amanuel2** [comment]
@rm-hull ok so I'm trying to understand here what is host and target environment... As it says [source : http://www.landley.net/writing/docs/cross-compiling.html] "The computer the compiler runs on is called the host, and the computer the new programs run on is called the target. When the host and target are the same type of machine, the compiler is a native compiler. When the host and target are different, the compiler is a cross compiler.[2]" .. So basically the host is.. basically, my computer i use to program this os. and the target environment is the actual OS architecture? and since my computer is x86-64 .. it is a cross compiler since I am writing an os for x86 as for now... but later when i write for x86-64 technically I am using a native compiler ... Is what I'm saying right? And one more thing , i see arm-none-eabi-  as suppose to ARM or arm64 . I'm guessing there is no 64 bit and 32-bit mode in ARM architecture ? If so ARM Is 64 or 32 bit? And yes, it would be awesome if you can do a refresh on this cross compiler!!!

**Comment by amanuel2** [comment]
Ok well , it would be cool if you can expand the target environment's :smile:

**Comment by rm-hull** [comment]
Yes I think your understanding is about right.  Here is where I built the current toolset from http://wiki.osdev.org/GCC_Cross-Compiler. This goes into a bit more detail.

There is only a 32bit arm support for a target environment but the  tools have been compiled for i686 and x86_64 host environments. I only did this as I wanted to build for raspberry pi (which until only recently was only 32 bit) but I have different Linux servers which are 32 and 64 bit.

I'll have a look at updating versions in the next few days and then the possibility of adding mips

**Comment by amanuel2** [comment]
@rm-hull Yea updating the version would be real nice.. that wiki is actually not the best of the kind. I will rely on this repo for Cross Compiler ... just try to upate the version and add mips if you can.. later i would branch of this repo and make another Cross Compiler when i have to many archs.

**Comment by rm-hull** [comment]
GCC version has been updated to 6.2.0. 

I have added a MIPS cross-compiler as well.
