### ISSUE TITLE
Don't call x86_64 targets i686

### ISSUE THREAD

**Issue by amanuel2** [rm-hull/barebones-toolchain#5]
I686 is only for 32 bit architectures, not 64 bit ones. Name them. X86_64

**Comment by rm-hull** [comment]
There isn't a 64-bit target for Intel x86 family, only 32-bit ... that is why it is called i686.

**Comment by amanuel2** [comment]
@rm-hull yes there is.. It's called x86_64 target. 64 bit target for the x86 Intel family

**Comment by rm-hull** [comment]
Haven't we been through this before on issue #3 ?

> the first i686 or x86_64 is the **host** environment and the subdirectory of i686-elf or arm-none-eabi denote the **target** environment.

```
$ tree -L 3
.
├── cross
│   ├── i686
│   │   ├── arm-none-eabi
│   │   ├── bin
│   │   ├── i686-elf
│   │   ├── lib
│   │   ├── libexec
│   │   ├── mips
│   │   └── share
│   └── x86_64
│       ├── arm-none-eabi
│       ├── bin
│       ├── i686-elf
│       ├── lib
│       ├── libexec
│       ├── mips
│       └── share
├── README.md
└── setenv.sh
```

If it were to ever support macOS, there would be a directory under `cross` called something like `darwin`, and then the same set of sub-directories (arm-non-eabi, bin, i686-elf, lib, libexec, mips, etc) under that

**Comment by amanuel2** [comment]
Yes we have and I do indeed still retain that information.  But what I am talking about is not the host environment but the target environment.  So are you saying you dont support x86_64 target environment (environment the OS your making will run under)? Because the only target environment I see is I686-elf which denotes its a 32 bit architecture

**Comment by rm-hull** [comment]
>  you dont support x86_64 target environment 

 Yes, correct - the only Intel -family x86 target environment is 32-bit i686.

**Comment by rm-hull** [comment]
Sorry I should've rephrased my earlier comment as: 

> "There isn't a 64-bit target _in this project_ for Intel x86 family, only 32-bit ... that is why it is called i686."

Apologies if this caused confusion :smiley:

**Comment by amanuel2** [comment]
Oh didn't know. Well after months I will work on the 64 bit system. And BoneOS.org relies on this repo for the cross compiler. If you can have 64bit arch setup anytime this month that will be great :)
