### ISSUE TITLE
i686-elf-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found

### ISSUE THREAD

**Issue by lholliger** [rm-hull/barebones-toolchain#7]
When  i run the command `i686-elf-gcc -T linker.ld -o myos.kernel -ffreestanding boot.o kernel.o -nostdlib -lgcc` (from OSDev), end up getting this error:
`i686-elf-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found`

**Comment by rm-hull** [comment]
@DatOneLefty - Can you trying pulling the latest master from github and trying again --> it looks like there were some missing symbolic links (now added in commit 7d17af6)

Let me know if that works for you

**Comment by lholliger** [comment]
It seems to have worked! Thank you!

**Comment by Noodlez1232** [comment]
I seem to still be having this issue

Using the code `i686-elf-gcc -T linker.ld -o $OUT -ffreestanding -nostdlib *.o -lgcc`
