### ISSUE TITLE
Am I allowed to package this in my own repository?

### ISSUE THREAD

**Issue by j4cobgarby** [rm-hull/barebones-toolchain#8]
I'm making a kernel and it seems like it would be a good idea to use this cross-compiler.

**Comment by rm-hull** [comment]
Of course -- just name-check this repo as a courtesy please :)

**Comment by j4cobgarby** [comment]
What do you mean a name-check? Thanks

**Comment by rm-hull** [comment]
Just acknowledge this repo as a source in your readme (or somewhere) along the lines of _'derived from https://github.com/rm-hull/barebones-toolchain'_
